name: csi-hostpath
namespace: kube-system
driver: hostpath.csi.ake.io
customLabels: {}
images:
  csi_hostpath:
    image: csi-hostpath
    tag: v0.7.1
  registrar:
    image: csi-node-driver-registrar
    tag: v2.3.0-amd64
  provisioner:
    image: csi-provisioner
    tag: v3.0.0-amd64
  resizer:
    image: csi-resizer
    tag: v1.3.0-amd64
  snapshotter:
    image: csi-snapshotter
    tag: v4.2.1-amd64
  snapshot_controller:
    image: snapshot-controller
    tag: v4.2.1-amd64
  health-monitor:
    image: csi-external-health-monitor-controller
    tag: v0.9.0-amd64
  attacher:
    image: csi-attacher
    tag: v3.3.0-amd64
agent:
  name: open-local-agent
  # This block device will be used to create as a Volume Group in every node
  # Open-Local does nothing if the device has been formatted or mountted
  device: /dev/vdb
  kubelet_dir: /var/lib/kubelet
  volume_name_prefix: local
  spdk: false
  # driver mode can be 'all' or 'node'
  # all: agent will start as csi controller and csi node
  # node: agent will start as csi node
  driverMode: node
controller:
  update_nls: "true"
storageclass:
  hostpath:
    name: hostpath-mock
monitor:
  # install grafana dashboard
  enabled: false
  # grafana namespace
  namespace: monitoring
global:
  RegistryDevURL: harbor.archeros.cn/dev/ake
  RegistryLibraryURL: harbor.archeros.cn/library/ake
