apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ostpath-mock
  labels:
    app: demo
driver: hostpath.csi.ake.io
deletionPolicy: Delete
parameters:
  csi.ake.io/readonly: "true"
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: snap-fio-vol-fio-2-0
spec:
  volumeSnapshotClassName: hostpath-mock
  source:
    persistentVolumeClaimName: fio-vol-fio-2-0
