apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: snap-fio-vol-fio-2-0
spec:
  volumeSnapshotClassName: hostpath-mock
  source:
    persistentVolumeClaimName: fio-vol-fio-2-0
